# Generated by Django 6.0.6 on 2026-06-25 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('OFERENTE', 'Oferente (Publica trabajos)'), ('CUIDADOR', 'Cuidador (Busca trabajos)')], max_length=20)),
                ('habilidades', models.TextField(blank=True, null=True, verbose_name='Habilidades o experiencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Pituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Pituto')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('pago', models.CharField(max_length=50, verbose_name='Monto a pagar (Ej: $15.000)')),
                ('tipo_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], default='tarea', max_length=20, verbose_name='Modalidad de pago')),
                ('flexibilidad', models.CharField(max_length=100, verbose_name='Etiqueta de Flexibilidad (Ej: Remoto / Noche)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitutos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Oferente creador')),
            ],
            options={
                'verbose_name': 'Pituto',
                'verbose_name_plural': 'Pitutos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulación')),
                ('pituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='app_pitutea.pituto', verbose_name='Pituto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL, verbose_name='Cuidador postulante')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
            },
        ),
    ]
