# Generated by Django 6.0.6 on 2026-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pitutea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categoria_interes',
            field=models.CharField(blank=True, choices=[('admin', 'Administrativo / Oficina'), ('hogar', 'Hogar / Limpieza'), ('cuidado', 'Cuidado de Personas'), ('digital', 'Digital / Redes Sociales'), ('logistica', 'Logística / Reparto'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Categoría de mayor interés'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna de residencia'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='pituto',
            name='categoria',
            field=models.CharField(choices=[('admin', 'Administrativo / Oficina'), ('hogar', 'Hogar / Limpieza'), ('cuidado', 'Cuidado de Personas'), ('digital', 'Digital / Redes Sociales'), ('logistica', 'Logística / Reparto'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría del trabajo'),
        ),
        migrations.AddField(
            model_name='pituto',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna (Dejar en blanco si es Remoto)'),
        ),
    ]
