# Generated by Django 6.0.6 on 2026-07-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pitutea', '0002_perfil_categoria_interes_perfil_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='carnet_cuidador',
            field=models.FileField(blank=True, null=True, upload_to='carnets/', verbose_name='Carnet de Cuidador'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT'),
        ),
    ]
