# Generated by Django 6.0.6 on 2026-07-10 04:55

import app_pitutea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pitutea', '0004_perfil_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='carnet_cuidador',
            field=models.ImageField(blank=True, null=True, upload_to='carnets/', validators=[app_pitutea.models.validar_tamano_imagen], verbose_name='Carnet de Cuidador'),
        ),
    ]
