# Generated by Django 6.0.6 on 2026-07-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pitutea', '0005_alter_perfil_carnet_cuidador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pituto',
            name='pago_anterior',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Monto anterior (tachado)'),
        ),
    ]
