# Generated by Django 6.0.6 on 2026-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pitutea', '0006_pituto_pago_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado_verificacion',
            field=models.CharField(choices=[('NO_VERIFICADO', 'No verificado'), ('PENDIENTE', 'Autorizado Pendiente Verificación'), ('VERIFICADO', 'Verificado'), ('BLOQUEADO', 'Bloqueado'), ('INACTIVO', 'Inactivo')], default='NO_VERIFICADO', max_length=30, verbose_name='Estado de Verificación'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='observaciones_verificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Verificación'),
        ),
    ]
