# Generated by Django 6.0.6 on 2026-07-14 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pitutea', '0007_perfil_estado_verificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pituto',
            name='calificacion_a_cuidador',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Calificación al cuidador (1-5)'),
        ),
        migrations.AddField(
            model_name='pituto',
            name='calificacion_a_oferente',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Calificación al oferente (1-5)'),
        ),
        migrations.AddField(
            model_name='pituto',
            name='comentario_a_cuidador',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario al cuidador'),
        ),
        migrations.AddField(
            model_name='pituto',
            name='comentario_a_oferente',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario al oferente'),
        ),
        migrations.AddField(
            model_name='pituto',
            name='cuidador_seleccionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pitutos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Cuidador seleccionado'),
        ),
        migrations.AddField(
            model_name='pituto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('OTORGADO', 'Trabajo Otorgado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20, verbose_name='Estado del Pituto'),
        ),
        migrations.AddField(
            model_name='pituto',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
    ]
