# Generated by Django 6.0.6 on 2026-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pitutea', '0008_pituto_calificacion_a_cuidador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Región'),
        ),
    ]
